# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos64_ja"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/3657281/centos64_ja.box"

  config.vm.define :web1 do |web|
    web.vm.network :private_network, ip: "192.168.33.14"
  end

  config.vm.synced_folder "../", "/var/www/html/", :create => true, :owner=> 'vagrant', :group=>'vagrant', :mount_options => ['dmode=777,fmode=755']

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  VAGRANTFILE_API_VERSION = "2"

  Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
     config.vm.box = "precise64"
     config.vm.box_url = "http://files.vagrantup.com/precise64.box"

     config.vm.network :forwarded_port, guest: 80, host: 8080
     config.vm.provision "shell", inline: <<-EOT
     apt-get update
     apt-get install -y apache2
     rm -rf /var/www
     ln -fs /vagrant /var/www
     echo "<h1>Hello, Vagrant Cloud.</h1>" > /vagrant/index.html
     EOT
  end

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "base"
    chef.add_recipe "php-mysql-httpd"
#    chef.add_recipe "php-api"
#    chef.add_recipe "composer"
#    chef.json = {
#      :composer => {
#        :install_path => "/usr/local/bin"
#      }
#    }
  end
end
